### PR TITLE
Lejos Project Commit

### PR DESCRIPTION
**Pull request by Acoolwolf96**

### CODE REVIEW

**Comment by Acoolwolf96** [comment]
Guys, please go through the code and make sure everything is ok

**Review by keshavsapkota3 — COMMENTED** [review]
All is good

**Comment by keshavsapkota3** [comment]
All is good

**Comment by atenidkoye** [comment]
i can't see any code. maybe it hasn't been uploaded yet?

**Comment by Acoolwolf96** [comment]
> i can't see any code. maybe it hasn't been uploaded yet?

you can find codes in commits

**Review by keshavsapkota3 — APPROVED** [review]
Kaiki on ihan hyvin

**Review by atenidkoye — COMMENTED** [review]
Everything looks good!

**Comment by atenidkoye** [comment]
Well structured.

**Comment by atenidkoye** [comment]
Well indented

**Comment by atenidkoye** [comment]
Approved.

**Review by atenidkoye — COMMENTED** [review]
All good. Approved!

**Review by atenidkoye — APPROVED** [review]
Everything looks good! Approved.

**Pull request merged**
